version = 1

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "meteor",
    "vue",
    "angularjs",
    "ember",
    "angular"
  ]

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  bootstrap_files = ["3000"]

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["300"]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "1.30.0"

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/1989shack/1989shack.com"
  dependencies_vendored = true

[[analyzers]]
name = "test-coverage"
enabled = true